<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TaskController;

Route::middleware('auth')->group(function () {
    // Task Resource Routes
    Route::resource('tasks', TaskController::class);
    
    // Optional: Explicit route definitions if needed later
    // Route::get('/tasks', [TaskController::class, 'index'])->name('tasks.index');
    // Route::get('/tasks/create', [TaskController::class, 'create'])->name('tasks.create');
    // etc...
});

// Authentication Routes (generated by Breeze)
require __DIR__.'/auth.php';